### ISSUE TITLE
Plugin doesn't read AWS IAM Role

### ISSUE THREAD

**Issue by andrewkaczynski** [Kong/kong-plugin-liamp#21]
I have a setup with kong on EKS. I have assigned the role to kong with full access to lambdas in my environment (via kube2iam). The role is good, as it was tested on other pod which can easily invoke the lambda. Kong returns below error when trying GET on given path:

```
2020/01/15 21:15:55 [error] 24#0: *19450 [kong] handler.lua:167 [aws-lambda] either 'signing_key' or 'secret_key' must be provided, client: 10.10.2.33, server: kong, request: "GET /lambda-test HTTP/1.1", host: "domain.example"
10.10.2.33 - - [15/Jan/2020:21:15:55 +0000] "GET /lambda-test HTTP/1.1" 500 42 "-" "curl/7.65.3"
```

My config is as follow:
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: api-get-plugin
  namespace: bitnet
config:
    function_name: [get-lambda]
    forward_request_body: true
    forward_request_headers: true
    forward_request_method: true
    invocation_type: RequestResponse
plugin: aws-lambda

kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    kubernetes.io/ingress.class: kong
    plugins.konghq.com: api-get-plugin
  name: api
spec:
  rules:
  - host: domain.example
    http:
      paths:
      - backend:
          serviceName: kong-kong-proxy
          servicePort: 8000
        path: /lambda-test
```
The only supported way is to add static keys to the KongPlugin object ? thanks!
